### ISSUE TITLE
Hyporrhoe with gorgon

### ISSUE THREAD

**Issue by gugushvili** [neanes/neanes#1007]
A hyporrhoe with gorgon on top must be understood quantitatively as in the attached picture. However, in Neanes the gorgon goes by default with the second apostrophos of the hyporrhoe (not envisioned by the theory books that I know of), while if you attach it to the first character (first apostrophos) by choosing number 1 instead of 2 in **Neume Select**, it becomes visibly misaligned.

This should be corrected.

Just in case: hapli below hyporrhoe goes with the second apostrophos.

![Image](https://github.com/user-attachments/assets/e9aff678-475e-4d7e-b7c4-a2d6e13b2b0a)

**Comment by danielgarthur** [comment]
The UI regarding selecting secondary/tertiary neumes is not great and needs to be improved. I'm thinking maybe each neume that supports multiple neumes should have those neumes either spelled out or the neume should be displayed, as opposed to 1, 2, 3, which is confusing.

The only bug that I see is that if you select "1", and add a gorgon, it is misaligned. This is because the gorgon is not allowed on the second apostrofos, and so the font doesn't support this. Choosing the gorgon in this case should either do nothing, or always assign the gorgon to the first apostrofos and never to the second.

As far as playback goes, I couldn't find any issue when doing the following.

- Click ison
- Click yporroe
- Click gorgon
- Click "Play"

The playback correctly puts the gorgon on the first apostrofos of the yporroe.

**Comment by danielgarthur** [comment]
As a more elaborate example of it working correctly, the following results in the same notes being placed twice with the same rhythm:
![Image](https://github.com/user-attachments/assets/24d42591-1e78-48fd-aabd-f837cfaa5cf1)

Tested in 0.4.51.

**Comment by gugushvili** [comment]
Maybe for back compatibility numbers 1 & 2 should give the same visual result, even though only the first apostrophos with gorgon is possible notationally. Playback is okay.
