### ISSUE TITLE
Low Ison Marking Playback

### ISSUE THREAD

**Issue by PeTH2** [neanes/neanes#1136]
Linux, ver. 0.4.58

When virtual notes are applied, but a low ison (below low Zo) is applied, the Ison marking plays an octave up. Also potentially related is that the Low Di ison in Soft Chomatic plays back a little flat, and out of tune with the main note.

Virtual notes:

https://github.com/user-attachments/assets/7688d1a3-bd3b-4300-9fd7-6cb49e4e6b3b

Low Ison, Soft Chromatic Di compares with other fthoras:

https://github.com/user-attachments/assets/ab1e4c36-e964-41ae-8033-a03fc0c605b0

**Comment by danielgarthur** [comment]
Thanks. I found the issue in the code. When transposition occurs, the map from ison to frequency does not account for the transposition if it falls outside the standard ison range (non-transposed).

**Comment by danielgarthur** [comment]
I have a fix to expand the range of the ison to be the same range as that of notes that will be released soon.

For the low THI issue, I'm not sure what to do yet. In the soft chromatic scale, low THI is not an octave away from THI.

Using western notes as an approximation, the soft chromatic scale descends as follows.
G F E Db C Bb A Gb F

So low THI would be flat compared to the high THI.

So the question is: how is low THI ison traditionally interpreted? Is it always an octave lower than the normal THI, or is it the low THI according to the scale? Do you have some examples of using the low THI with the soft chromatic scale? I usually think of it being used with the diatonic scale. 

I think I have seen some scores use a low THI with soft chromatic in cases where it seems more correct to use a high THI and let the chanters decide which octave to sing it or to do a double ison (depending on whether anyone can sing that low).

**Comment by PeTH2** [comment]
I was able to find at least one recording of the Second Mode Kekragaria with a cosistent low Di ison.

https://youtu.be/578MFGIq9-g?feature=shared

Nevertheless I have also tended to hear it on when final endings resolve to Di. Maybe there could be a checkbox or something that can allow an override of Ison playback in soft chromatic modes?

**Comment by basil** [comment]
> Using western notes as an approximation, the soft chromatic scale descends as follows: G F E D♭ C B♭ A G♭ F

In practice, soft chromatic melodies of the modern heirmologic and sticheraric genres never go below the B♭ / C mentioned above, and even then that movement is accompanied by a modulation to the hard chromatic scale (see Section F of https://music.samonastery.org/Formula2.pdf for examples). So this question is mostly theoretical and is only relevant to obscure genres or compositions. Even if such a melody existed, it would most likely be descending to the F mentioned above, so I am having a hard time imagining a case where the G♭ ison mentioned above would ever be desirable in practice. Similarly, I cannot ever imagine a [not low] A♭ ison in a soft chromatic melody either.

I do not see a good reason to use a (Δ↓) ison marking in a score unless the melody is descending to low Di, as it forces a particular performance practice on the singer. A neutral notational style would use a (Δ) ison marking when the melody is revolving around [not low] Di. There are many schools of thought about how to chant the ison when the melody is revolving around [not low] Di, particularly because in these cadences the melody is often also going down to [not low] Vou and some perceive it to be a problem when the ison is above the melody. Some chant ison on Vou, while some do not. Some chant ison in unison with the melody as it dips below Di, while others do not. Some chant the Di ison an octave lower to stay out of the melody's way, while others do not. This all depends on your particular style of performance practice.

Since I do not think the (Δ↓) is a good notational choice in this case, it would suit me just fine if the software did not go out of its way to special-case this scenario in the playback subsystem. But I do think it would make sense to support playing back a (Δ) ison marking (or any other [not low] ison marking) an octave lower for those who prefer this style of performance.
