### ISSUE TITLE
[BUG] Page Numbers not appearing.

### ISSUE THREAD

**Issue by mattsmi** [neanes/neanes#556]
**This bug was found in 0.4.17**

- [x] Desktop

**Describe the bug**
After ticking/checking Include Footer and ensuring that First Page Number is set to 1, I expect the page number to appear in the footer. There appears to be no menu choice that would otherwise insert the page number.

**To Reproduce**
Choose to include a footer, and ensure that the First Page Number value is a valid value.

**Expected behaviour**
Expected page number to appear in the footer.

**Comment by neobabis** [comment]
Read the GUIDE [here](https://neanes.github.io/neanes/guide/advanced.html#page-numbers)
'To insert a page number in the header/footer, type $p. When the document is printed, the token $p will be replaced with the correct page number in the header/footer of each page.'

**Comment by mattsmi** [comment]
1. Thank you! I looked everywhere and searched within the Guide, but could not find any information.
2. However, Inserting a Footer, and then typing $p into the footer in either a LTR document or a RTL document gave no page number when exporting to PDF.
3. When I try File, Print — in case the functionality is only available under Print instead of Exporting as PDF — NEANES just disappears silently.

It seems like there is still a bug in the functionality somewhere.

**Comment by danielgarthur** [comment]
What I'm seeing is that if you try to export while the footer text box is selected, and hence `$p` is visible, then the resulting PDF contains `$p` instead of the page number. 
<img width="209" alt="image" src="https://github.com/neanes/neanes/assets/4132779/6a657d4f-116b-440d-a9b9-0de6bac9db7d">

But if I first click another element, so that the `$p` turns into a page number in Neanes, then export, the page number appears.

<img width="134" alt="image" src="https://github.com/neanes/neanes/assets/4132779/71e41d4e-b7cd-45a0-b98e-d3dfe07b9bf6">

So that would indeed be a minor bug. Is this what you are seeing?

**Comment by mattsmi** [comment]
Yes. At least there is a simple work-around. Thanks, Daniel. I'm sorry I did not try to click elsewhere.
NB When typing $p into an RTL document, the result is "p$", but clicking into the score still resolves it to the page number.

**Comment by danielgarthur** [comment]
Fixed in [0.4.18](https://github.com/neanes/neanes/releases/tag/v0.4.18).
