### ISSUE TITLE
Inline text box width incorrect with multi-line text

### ISSUE THREAD

**Issue by basil** [neanes/neanes#646]
When entering multi-line text into an inline text box (with shift-enter), the width of the inline text box is erroneously calculated as if all the text were on a single line.

**Comment by danielgarthur** [comment]
What I'm not sure about here is why I'm even attempting to calculate the text box (inline or other) when I already know the height via `HTMLElement`'s `scrollHeight`... I'll take a closer look at this to see if this can be greatly simplified.

This is also relevant because of the use of `pretty` and `balanced`, which means my simple method of calculating the text width with `TextMetrics` may calculate the wrong height. If the browser can already tell me the height, then I should try to calculate it by hand.
