### ISSUE TITLE
Moving Panels

### ISSUE THREAD

**Issue by isvarnas** [neanes/neanes#775]
It could be useful if we can move the "Quantitative neumes" panel  το the right side of the window.

**Comment by danielgarthur** [comment]
I don't see any issue with adding a setting to dock the panel to the right, but I would like to understand the reason for the request first. What is the primary motivation for wanting the panel on the right? I want to make sure that this isn't part of a larger request or issue that would require more planning.

**Comment by basil** [comment]
I can't speak to the original poster's motivation, but the UI has definitely felt a bit inflexible to me at times. On my 3840 × 2160 display, moving the mouse from the main score to the toolbars can require a lot of mouse movement back and forth. The fact that the zoom only goes up to 200% doesn't help—the score doesn't come close to filling my screen. Consider also that only one document can be visible at a time and that #651 isn't supported, and things can start to feel a bit rigid.

In traditional desktop publishing software like InDesign or Finale, the toolbars can generally be docked to any side of the screen, or floated and moved around. I would often float the note toolbar and move it to where I was editing to minimize mouse movement back and forth. Implementing that in Neanes would be a clear usability win to me. In traditional desktop publishing software, each document is also a window within the application (modulo some differences on macOS), so you can do a lot with a high-resolution screen by laying out a few documents at the same time and using one set of toolbars to interact with all of those documents.

I hope it is obvious that I don't want to sound unappreciative (especially because I've been a bit too busy with work to contribute recently), and these flaws are relatively minor overall—certainly nothing I've felt compelled to file an issue about. Good UIs in open source software are few and far between, and the existing UI is certainly quite decent. It's possible that this Neanes is the best page layout application ever written for the Electron platform, which would be an achievement in and of itself (Byzantine music aside). And of course this is all light years ahead of using Word macros. So thanks again and thanks for reading this post. :smile:

**Comment by isvarnas** [comment]
Actually it is not an issue. 
It is my personal preference. 
I am using the mouse with my right hand to add quantitative neumes and my left hand to add supporting neumes with keyboard shortcuts. In my personal opinion, in that way I minimise mouse movements and speed up the process of creating documents.
Anyway, the application is the best solution regarding byzantine notation.
Thank you very much!

**Comment by basil** [comment]
> I am using the mouse with my right hand to add quantitative neumes and my left hand to add supporting neumes with keyboard shortcuts.

This actually matches the way I use the application as well. As much as I've tried to learn the keyboard shortcuts for the quantitative neumes, they just haven't stuck in my mind yet. So I use the mouse to add them and use the keyboard to add supporting marks. This would actually be quite efficient if it weren't for the constant back and forth mouse movement.
