### ISSUE TITLE
General flat is not allowed after fthora

### ISSUE THREAD

**Issue by cryoranger** [neanes/neanes#863]
**This bug was found in**

- [x] Desktop
- [ ] Web App
- [ ] Both

**Describe the bug**
I am trying to write "Θεαρχιω Νεύματι" Doxastiko of 15th of August by Iakovos Protopsaltis from the "Αργόν Δοξαστάριον Ιακώβου (1888) τόμος Β'" which is a lesson that includes all eight modes. I have found the book from [analogion.com post](http://analogion.com/forum/index.php?threads/%C2%AB-%CE%91%CF%81%CE%B3%CF%8C%CE%BD-%CE%94%CE%BF%CE%BE%CE%B1%CF%83%CF%84%CE%AC%CF%81%CE%B9%CE%BF%CE%BD%C2%BB-%CE%99%CE%B1%CE%BA%CF%8E%CE%B2%CE%BF%CF%85-%CE%A0%CF%81%CF%89%CF%84%CE%BF%CF%88%CE%AC%CE%BB%CF%84%CE%BF%CF%85-%CE%A7%CE%BF%CF%85%CF%81%CE%BC%CE%BF%CF%85%CE%B6%CE%AF%CE%BF%CF%85-%CE%A7%CE%B1%CF%81%CF%84%CE%BF%CF%86%CF%8D%CE%BB%CE%B1%CE%BA%CE%BF%CF%82-%CE%9A%CF%89%CE%BD%CF%83%CF%84%CE%B1%CE%BD%CF%84%CE%B9%CE%BD%CE%BF%CF%8D%CF%80%CE%BF%CE%BB%CE%B7-1%CE%B7-%CE%AD%CE%BA%CE%B4%CE%BF%CF%83%CE%B7-%CF%84-%CE%91%CE%84-%CE%BA%CE%B1%CE%B9-%CE%92%CE%84-1836-2%CE%B7-%CE%AD%CE%BA%CE%B4%CE%BF%CF%83%CE%B7-%CF%84-%CE%91%CE%84-%CE%BA%CE%B1%CE%B9-%CE%92%CE%84-1888.5332/post-254896).

My issue can be seen in the following screenshot from the book:
![image](https://github.com/user-attachments/assets/13f91329-667c-4501-b143-f4641c44313d)

I am not allowed to enter the "general flat" as neanes thinks that this neume is a Zo' rather than a Ke.
I think the issue is caused by the end of the plagal second part the diatonic Ga fthora is placed on Di neume at "νε" syllable to change the mode.

I have another example of the same lesson from another book:
![image](https://github.com/user-attachments/assets/f4619363-5a10-4878-966f-89bd0bb78eff)

From another composition of the same Doxastikon from Stefanos Lampadarios as seen in "Μουσική Κυψέλη Στεφάνου Λαμπαδαρίου (2007) τόμος Β'" we see the something similar on "και" syllable:
![image](https://github.com/user-attachments/assets/52eee60b-b4e2-4ac1-9ffa-1a9bc85c67ab)

**To Reproduce**
load my writing [Θεαρχίω Νεύματι (Ιακώβου).zip](https://github.com/user-attachments/files/16345042/default.zip)
see the issue in the bellow screenshot:
![image](https://github.com/user-attachments/assets/cd967132-a90e-43e9-b143-03cba06c8c9c)

**Expected behavior**
I think that neanes should take into account the change of the note from the fthora and I would be able to add the General flat.

**Desktop Version (please complete the following information, if applicable):**

- OS: Windows 10
- Version 0.4.48

**Comment by danielgarthur** [comment]
In the Page Setup dialog you can check "Disable Fthora Restrictions" which will allow any fthora anywhere. Audio playback will most likely not function correctly, as these special cases are not taken into account.

Whether Neanes should allow fthora on parallage notes without needing to check the box... I'm not sure. If there were clearly defined rules that made sense, they could be included, but this seems like the kind of edge use case that "Disable Fthora Restrictions" was designed for.

**Comment by basil** [comment]
I would vote in favor of improving the fthora validation feature to take into account the transposed note. The software is already aware of both the physical note and the transposed note (for example, to display computed note indicators), and it would be nice if the fthora validation could take that into account. I refuse to check the "Disable Fthora Restrictions" checkbox, as it is a global (rather than per-score) setting, and I generally want the safety of fthora validation. But this has some downsides.

For example, I have a number of Axion Estins in Makam Hicâzkâr. The originals are sometimes notated with a basis of Ni as "Plagal Fourth Chromatic", but Neanes fthora validation makes a basis of Ni untenable for such pieces. I ended up transposing all of them to have a basis of Pa and labeling them as "Plagal Second Mode (Heptaphonic)", which is certainly musicologically justified. But if Neanes supported this, I might move them back down to a basis of Ni to match the way the original composers notated these pieces.

In any case, one doesn't need to look to esoteric makamlar to find examples of where this limitation is annoying; see issue #215. Many Anastasimataria write Second Mode canons using a basis of Vou, which exposes the same issue. If fthora validation took into account the transposed note, this class of problems would be solved.

Another piece where this issue has come up is my Axion Estin in Makam Şevk-Efzâ (adapted from Misael Misaelides), but unlike the Anastasimatarion, this is truly an edge case. In fact, I have a Romanian book that (as I recall) presents this piece in Romanian in both the original whacky scale (with a basis of Zo) as well as a (more sane) transposed version with a basis of Pa.

> If there were clearly defined rules that made sense, they could be included

What kind of rules are you looking for?

**Comment by cryoranger** [comment]
Many thanks for the workaround provided!
I agree with Basil that the "Disable Fthora Restrictions" will disable a very useful feature that protects me from making mistakes.

I have another case where the fthora is not taken into account. Let's see the same Doxastikon, composed by Stefanos Lampadarios as found in "Μουσική Κυψέλη Στεφάνου Λαμπαδαρίου (2007) τόμος Β'":
![image](https://github.com/user-attachments/assets/1e3657c3-2c09-42f0-be0d-8286e216f1a7)

Writing this in Neanes produces this:
![image](https://github.com/user-attachments/assets/0a58eb2b-8683-4db3-ab01-7d3b86361b79)
[Θεαρχίω Νεύματι (Στεφάνου).zip](https://github.com/user-attachments/files/16358146/default.zip)

As you can see, the martyria at the end of the screenshot is not calculated correctly because the diatonic fthora of Ke at the beginning of the verse "καταλαβόντες" is not taken correctly into account.

I have another example from another lesson similar to the above but with chromatic fthoras if you need.

PS: I am aware that I can override the martyria to display the correct one, but this auto-calculation feature of Neanes is very useful to help finding mistakes and also easy the work of writing scores.

**Comment by danielgarthur** [comment]
Somewhat related: should `Disable Fthora Restrictions` be added to the neume toolbar as a per neume option? This way you don't have to disable fthora safety checking globally, but can still account for the occasional unusual fthora?

**Comment by basil** [comment]
I would be satisfied enough if the existing fthora validation safety was extended to cover transposed/virtual notes as in https://github.com/neanes/neanes/issues/863#issuecomment-2246824103.

**Comment by danielgarthur** [comment]
@basil Should the enharmonic fthora button be disabled based solely on the current virtual note, or should the real note be considered, too?

In the following example, should the enharmonic fthora be allowed on both oligons, or only the second one?
![Image](https://github.com/user-attachments/assets/7b6a3568-e781-43aa-bebc-7cacc7225e25)

I'm leaning toward only the virtual note should be considered, but I'm not sure.

**Comment by basil** [comment]
@danielgarthur I think it should be based solely on the current virtual note; i.e., only the first oligon should allow an enharmonic fthora in your example. The purpose of fthora validation, like a type system, is to provide safety and prevent the user from easily getting into nonsensical scenarios while also supporting common scenarios without getting in the way. A policy of considering only the physical note (i.e., the status quo) isn't flexible enough to support common scenarios, while a policy of considering both the physical and virtual note seems flexible to the point of diluting the value of the validation feature. A policy of considering only the virtual note seems to strike a good balance and would solve the vast majority of the problems I have encountered.
